// Generated by https://quicktype.io

export interface CombinedData {
  id: string;
  entity_type_name: string;
  checklistName: string;
  room?: string;
  amount: number;
  bill_of_quantity: BillOfQuantity[];
}

export interface BillOfQuantity {
  id: string;
  position: string;
  type: string;
  shortText: string;
  longText: string;
  quantity: number;
  totalTime: number;
  unitTag: string;
  createdAt: string;
  updatedAt: string;
  dxfElementId: string;
  unitPrice: number;
  totalPrice: number;
}
