// Generated by https://quicktype.io

export interface IGaeb {
  position: string;
  type: string;
  unitPrice: number;
  quantity: number;
  unitTag: string;
  shortText: string;
  longText: string;
  totalPrice: number;
  totalTime: number;
}
